langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3.5-plus
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3.5-plus
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10

  community:
    redis:
      host: localhost
      port: 6379
      index-name: consultant-doc-index-v2
      prefix: "consultant-doc-v2:"
      metadata-keys:
        - userId
        - documentId
        - fileName
        - fileType
logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  sql:
    init:
      mode: always
      encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/consultant?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

# Sa-Token 配置
sa-token:
  token-name: satoken         # Token 名称（请求头/Cookie 键名）
  timeout: 2592000            # Token 有效期（秒），30天
  active-timeout: -1          # Token 活跃校验，-1 不启用
  is-concurrent: true         # 允许同账号多地登录
  is-share: true              # 同账号多次登录共用同一个 Token
  token-style: uuid           # Token 风格
  is-log: false               # 关闭日志
mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  ai:
    vision-model: qwen-vl-plus
  minio:
    endpoint: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: ros123
